[package]
name = "flux-opt"
version = "0.1.0"

edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flux-common.workspace = true
flux-config.workspace = true
flux-errors.workspace = true
flux-macros.workspace = true
flux-rustc-bridge.workspace = true
serde.workspace = true
serde_json.workspace = true
liquid-fixpoint.workspace = true

itertools.workspace = true
rustc-hash.workspace = true

tracing = "0.1"


[package.metadata.rust-analyzer]
rustc_private = true

[lints]
workspace = true
