[package]
name = "flux-fixpoint"
version = "0.1.0"

edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flux-common.workspace = true

derive-where.workspace = true
itertools.workspace = true
serde.workspace = true
serde_json = "1.0"

[package.metadata.rust-analyzer]
rustc_private = true

[lints]
workspace = true
