[package]
name = "flux-desugar"
version = "0.1.0"

edition.workspace = true

[lib]
doctest = false
test = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flux-common.workspace = true
flux-config.workspace = true
flux-errors.workspace = true
flux-macros.workspace = true
flux-middle.workspace = true
flux-syntax.workspace = true
itertools = "0.11"

[package.metadata.rust-analyzer]
rustc_private = true

[lints]
workspace = true
