[package]
name = "flux-middle"
edition.workspace = true
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flux-arc-interner.workspace = true
flux-common.workspace = true
flux-config.workspace = true
flux-errors.workspace = true
flux-macros.workspace = true
flux-rustc-bridge.workspace = true
flux-syntax.workspace = true


liquid-fixpoint.workspace = true

anstream.workspace = true
anstyle.workspace = true
bumpalo.workspace = true
bitflags.workspace = true
dashmap.workspace = true
ena.workspace = true
hashbrown.workspace = true
itertools.workspace = true
rustc-hash.workspace = true
serde.workspace = true
serde_json.workspace = true
toposort-scc.workspace = true
tracing = "0.1"

[package.metadata.rust-analyzer]
rustc_private = true

[lints]
workspace = true
