[package]
name = "flux-macros"
version = "0.1.0"

edition.workspace = true

[lib]
proc-macro = true

[dependencies]
annotate-snippets = "0.8.0"
fluent-bundle = "0.15.2"
fluent-syntax = "0.11"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
synstructure = "0.13.0"
unic-langid = { version = "0.9.1", features = ["macros"] }

[lints]
workspace = true
