[package]
name = "flux-tests"
version = "0.1.0"

edition.workspace = true

[lib]
doctest = false
test = false

[dev-dependencies]
compiletest_rs = "0.8"
itertools = "0.10"

[package.metadata.rust-analyzer]
rustc_private = true
