[package]
name = "flux-tests"
version = "0.1.0"

edition.workspace = true

[lib]
doctest = false
test = false

[dev-dependencies]
itertools.workspace = true

compiletest_rs = "0.10"

[package.metadata.rust-analyzer]
rustc_private = true

[lints]
workspace = true
