[package]
name = "flux-syntax"
version = "0.1.0"

edition.workspace = true

[lib]
doctest = false
test = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flux-errors.workspace = true
lalrpop-util = "0.20"

[build-dependencies]
lalrpop = "0.20"

[package.metadata.rust-analyzer]
rustc_private = true
