[package]
edition.workspace = true
name = "flux-infer"
version = "0.1.0"

[dependencies]
flux-common.workspace = true
flux-config.workspace = true
flux-errors.workspace = true
flux-middle.workspace = true

liquid-fixpoint.workspace = true

itertools.workspace = true
pad-adapter.workspace = true

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
