[package]
edition.workspace = true
name = "flux-infer"
version = "0.1.0"




[dependencies]
flux-common.workspace = true
flux-config.workspace = true
flux-errors.workspace = true
flux-macros.workspace = true
flux-middle.workspace = true
flux-rustc-bridge.workspace = true

itertools.workspace = true
liquid-fixpoint.workspace = true
pad-adapter.workspace = true
rustc-hash.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
